import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useState, useEffect } from 'react';
import Students from '../components/students';
import Result from '../components/result';
import AddStudent from '../components/addstudent';

export default function Home() {
  const [pageInfo, setPageInfo] = useState({ activeTab: 'students', id: '' })
  const [serachID, setSerachID] = useState(null)
  const [input, setInput] = useState([])

  function saveData(i) {
    if (input.length > 0) {
      let arr = input.map(inp => inp.value);
      if (arr.includes('')) {
        alert("Fill all fields")
      } else {
        console.log(arr);
      }
    } else {
      alert("Nothing to save")
    }
  }
  return (
    <div>
      <Head>
        <title>Imapact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className='d-flex flex-column justify-content-center align-items-center ' style={{ marginTop: '5rem' }}>
        <div className='d-flex flex-column'>
          {
            input.map((inp, i) => (
              <div key={i} className='d-flex flex-row' style={{ padding: '2rem' }}>
                <input placeholder={inp.placeholder} value={inp.value} id={i} name={i} onChange={(e) => {

                  let dummayInput = [...input]
                  dummayInput[i].value = e.target.value
                  setInput(dummayInput)
                }}
                >
                </input>
                <button onClick={() => {
                  let dummyUI = [...input]
                  console.log(dummyUI.splice(i, 1));
                  setInput(dummyUI)
                }} > Delete</button>
              </div>
            ))
          }
        </div>
        <div>
          <button onClick={() => setInput([...input, { value: "", placeholder: "Enter Name", label: "Enter Value" }])}>ADD</button>
          <button onClick={() => saveData()}>SUBMIT</button>

        </div>

      </div> */}




      <main>
        <nav className="navbar navbar-expand-lg navbar-light bg-light i-px-1">
          <div className='d-flex flex-row justify-content-between align-items-center'>

            <button className="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span className="navbar-toggler-icon"></span>
            </button>

            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav mr-auto">
                <li className="nav-item  i-px-1 i-cur-ptr">
                  <a className="nav-link " onClick={() => setPageInfo({ ...pageInfo, activeTab: 'home' })}>Home </a>
                </li>
                <li className="nav-item i-px-1 i-cur-ptr">
                  <a className="nav-link" onClick={() => setPageInfo({ ...pageInfo, activeTab: 'students' })}>Students</a>
                </li>
                <li className="nav-item i-px-1 i-cur-ptr">
                  <a className="nav-link" onClick={() => setPageInfo({ ...pageInfo, activeTab: 'add' })}>Add</a>
                </li>
                <li className="nav-item i-px-1 i-cur-ptr">
                  <a className="nav-link" onClick={() => setPageInfo({ ...pageInfo, activeTab: 'result' })}>Result</a>
                </li>
              </ul>

              <div className="d-flex flex-row form-inline my-2 my-lg-0">
                <input className="form-control mr-sm-2" type="search" value={serachID} onChange={(e) => {
                  if (e.target.value == '') {
                    setSerachID(e.target.value)
                    setPageInfo({ ...pageInfo, id: null })
                  } else {
                    setSerachID(e.target.value)
                  }
                }
                } placeholder="Enter ID" aria-label="Search" />
                <button className="btn btn-outline-success my-2 my-sm-0" onClick={() => { setPageInfo({ ...pageInfo, id: serachID }) }}>Search</button>
              </div>
            </div>
          </div>
        </nav>
      </main >
      <div >
        {
          pageInfo.activeTab == 'students'
            ? <Students regno={pageInfo.id}></Students>
            : pageInfo.activeTab == 'add'
              ? <AddStudent />
              : pageInfo.activeTab == 'result'
                ? <Result></Result>
                : null
        }
      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div >
  )
}
